#!/bin/bash

rm -r /usr/local/lib/faust/android
mkdir /usr/local/lib/faust/android

cp build.gradle /usr/local/lib/faust/android
cp dsp_faust_interface.i /usr/local/lib/faust/android
cp Faust.iml /usr/local/lib/faust/android
cp gradlew /usr/local/lib/faust/android
cp local.properties /usr/local/lib/faust/android
cp settings.gradle /usr/local/lib/faust/android

cp -r app /usr/local/lib/faust/android
rm -r /usr/local/lib/faust/android/app/build
cp -r gradle /usr/local/lib/faust/android

cp architecture/android.cpp /usr/local/lib/faust

cp faust2android /usr/local/bin
