/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.grame.faust_dsp;

public class faustObject {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected faustObject(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(faustObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        faust_dspJNI.delete_faustObject(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void initFaust() {
    faust_dspJNI.faustObject_initFaust(swigCPtr, this);
  }

  public String getJSON() {
    return faust_dspJNI.faustObject_getJSON(swigCPtr, this);
  }

  public int getParamsCount() {
    return faust_dspJNI.faustObject_getParamsCount(swigCPtr, this);
  }

  public void startAudio() {
    faust_dspJNI.faustObject_startAudio(swigCPtr, this);
  }

  public float getParam(String arg0) {
    return faust_dspJNI.faustObject_getParam(swigCPtr, this, arg0);
  }

  public void setParam(String arg0, float arg1) {
    faust_dspJNI.faustObject_setParam(swigCPtr, this, arg0, arg1);
  }

  public void stopAudio() {
    faust_dspJNI.faustObject_stopAudio(swigCPtr, this);
  }

  public String getParamPath(int arg0) {
    return faust_dspJNI.faustObject_getParamPath(swigCPtr, this, arg0);
  }

  public faustObject() {
    this(faust_dspJNI.new_faustObject(), true);
  }

}
