/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.grame.faust_dsp;

public class faustObject {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected faustObject(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(faustObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        faust_dspJNI.delete_faustObject(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Para initFaust() {
    return new Para(faust_dspJNI.faustObject_initFaust(swigCPtr, this), true);
  }

  public void startAudio() {
    faust_dspJNI.faustObject_startAudio(swigCPtr, this);
  }

  public void processDSP() {
    faust_dspJNI.faustObject_processDSP(swigCPtr, this);
  }

  public void setParam(SWIGTYPE_p_float arg0) {
    faust_dspJNI.faustObject_setParam(swigCPtr, this, SWIGTYPE_p_float.getCPtr(arg0));
  }

  public void stopAudio() {
    faust_dspJNI.faustObject_stopAudio(swigCPtr, this);
  }

  public faustObject() {
    this(faust_dspJNI.new_faustObject(), true);
  }

}
