/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.grame.faust_dsp;

public class faust_dsp {
  public static void init(int arg0, int arg1) {
    faust_dspJNI.init(arg0, arg1);
  }

  public static int start() {
    return faust_dspJNI.start();
  }

  public static void stop() {
    faust_dspJNI.stop();
  }

  public static boolean isRunning() {
    return faust_dspJNI.isRunning();
  }

  public static int keyOn(int arg0, int arg1) {
    return faust_dspJNI.keyOn(arg0, arg1);
  }

  public static int keyOff(int arg0) {
    return faust_dspJNI.keyOff(arg0);
  }

  public static int pitchBend(int arg0, float arg1) {
    return faust_dspJNI.pitchBend(arg0, arg1);
  }

  public static String getJSON() {
    return faust_dspJNI.getJSON();
  }

  public static int getParamsCount() {
    return faust_dspJNI.getParamsCount();
  }

  public static float getParam(String arg0) {
    return faust_dspJNI.getParam(arg0);
  }

  public static void setParam(String arg0, float arg1) {
    faust_dspJNI.setParam(arg0, arg1);
  }

  public static void setVoiceParam(String arg0, int arg1, float arg2) {
    faust_dspJNI.setVoiceParam(arg0, arg1, arg2);
  }

  public static void setVoiceGain(int arg0, float arg1) {
    faust_dspJNI.setVoiceGain(arg0, arg1);
  }

  public static String getParamAddress(int arg0) {
    return faust_dspJNI.getParamAddress(arg0);
  }

}
