/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.grame.faust_dsp;

public class faust_dsp {
  public static void initFaust() {
    faust_dspJNI.initFaust();
  }

  public static void initFaustPoly() {
    faust_dspJNI.initFaustPoly();
  }

  public static String getJSON() {
    return faust_dspJNI.getJSON();
  }

  public static int getParamsCount() {
    return faust_dspJNI.getParamsCount();
  }

  public static void startAudio() {
    faust_dspJNI.startAudio();
  }

  public static void startAudioPoly() {
    faust_dspJNI.startAudioPoly();
  }

  public static void keyOn(int arg0, int arg1) {
    faust_dspJNI.keyOn(arg0, arg1);
  }

  public static void keyOff(int arg0) {
    faust_dspJNI.keyOff(arg0);
  }

  public static float getParam(String arg0) {
    return faust_dspJNI.getParam(arg0);
  }

  public static void setParam(String arg0, float arg1) {
    faust_dspJNI.setParam(arg0, arg1);
  }

  public static void setParamPoly(String arg0, float arg1) {
    faust_dspJNI.setParamPoly(arg0, arg1);
  }

  public static void stopAudio() {
    faust_dspJNI.stopAudio();
  }

  public static boolean isRunning() {
    return faust_dspJNI.isRunning();
  }

  public static String getParamPath(int arg0) {
    return faust_dspJNI.getParamPath(arg0);
  }

}
