/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.grame.faust_dsp;

public class faust_dspJNI {

  static {
    try {
        java.lang.System.loadLibrary("faust_dsp");
    } catch (UnsatisfiedLinkError e) {
        java.lang.System.err.println("native code library failed to load.\n" + e);
        java.lang.System.exit(1);
    }
  }

  public final static native long new_floatArray(int jarg1);
  public final static native void delete_floatArray(long jarg1);
  public final static native float floatArray_getitem(long jarg1, int jarg2);
  public final static native void floatArray_setitem(long jarg1, int jarg2, float jarg3);
  public final static native String new_charArray(int jarg1);
  public final static native void delete_charArray(String jarg1);
  public final static native char charArray_getitem(String jarg1, int jarg2);
  public final static native void charArray_setitem(String jarg1, int jarg2, char jarg3);
  public final static native void initFaust();
  public final static native String getJSON();
  public final static native int getParamsCount();
  public final static native void startAudio();
  public final static native float getParam(String jarg1);
  public final static native void setParam(String jarg1, float jarg2);
  public final static native void stopAudio();
  public final static native String getParamPath(int jarg1);
}
