/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.grame.faust_dsp;

public class faust_dspJNI {

  static {
    try {
        java.lang.System.loadLibrary("faust_dsp");
    } catch (UnsatisfiedLinkError e) {
        java.lang.System.err.println("native code library failed to load.\n" + e);
        java.lang.System.exit(1);
    }
  }

  public final static native long new_floatArray(int jarg1);
  public final static native void delete_floatArray(long jarg1);
  public final static native float floatArray_getitem(long jarg1, int jarg2);
  public final static native void floatArray_setitem(long jarg1, int jarg2, float jarg3);
  public final static native String new_charArray(int jarg1);
  public final static native void delete_charArray(String jarg1);
  public final static native char charArray_getitem(String jarg1, int jarg2);
  public final static native void charArray_setitem(String jarg1, int jarg2, char jarg3);
  public final static native void Para_cnt_set(long jarg1, Para jarg1_, int jarg2);
  public final static native int Para_cnt_get(long jarg1, Para jarg1_);
  public final static native void Para_cntHsliders_set(long jarg1, Para jarg1_, int jarg2);
  public final static native int Para_cntHsliders_get(long jarg1, Para jarg1_);
  public final static native void Para_cntVsliders_set(long jarg1, Para jarg1_, int jarg2);
  public final static native int Para_cntVsliders_get(long jarg1, Para jarg1_);
  public final static native long new_Para();
  public final static native void delete_Para(long jarg1);
  public final static native void faustObject_initFaust(long jarg1, faustObject jarg1_);
  public final static native String faustObject_getJSON(long jarg1, faustObject jarg1_);
  public final static native int faustObject_getParamsCount(long jarg1, faustObject jarg1_);
  public final static native void faustObject_startAudio(long jarg1, faustObject jarg1_);
  public final static native float faustObject_getParam(long jarg1, faustObject jarg1_, String jarg2);
  public final static native void faustObject_setParam(long jarg1, faustObject jarg1_, String jarg2, float jarg3);
  public final static native void faustObject_stopAudio(long jarg1, faustObject jarg1_);
  public final static native String faustObject_getParamPath(long jarg1, faustObject jarg1_, int jarg2);
  public final static native long new_faustObject();
  public final static native void delete_faustObject(long jarg1);
}
