/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.grame.faust_dsp;

public class faust_dspJNI {

  static {
    try {
        java.lang.System.loadLibrary("faust_dsp");
    } catch (UnsatisfiedLinkError e) {
        java.lang.System.err.println("native code library failed to load.\n" + e);
        java.lang.System.exit(1);
    }
  }

  public final static native void Para_cnt_set(long jarg1, Para jarg1_, int jarg2);
  public final static native int Para_cnt_get(long jarg1, Para jarg1_);
  public final static native void Para_zone_set(long jarg1, Para jarg1_, long jarg2);
  public final static native long Para_zone_get(long jarg1, Para jarg1_);
  public final static native long new_Para();
  public final static native void delete_Para(long jarg1);
  public final static native long faustObject_initFaust(long jarg1, faustObject jarg1_);
  public final static native void faustObject_startAudio(long jarg1, faustObject jarg1_);
  public final static native void faustObject_processDSP(long jarg1, faustObject jarg1_);
  public final static native void faustObject_setParam(long jarg1, faustObject jarg1_, long jarg2);
  public final static native void faustObject_stopAudio(long jarg1, faustObject jarg1_);
  public final static native long new_faustObject();
  public final static native void delete_faustObject(long jarg1);
}
