/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.grame.faust_dsp;

public class Para {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Para(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Para obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        faust_dspJNI.delete_Para(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCnt(int value) {
    faust_dspJNI.Para_cnt_set(swigCPtr, this, value);
  }

  public int getCnt() {
    return faust_dspJNI.Para_cnt_get(swigCPtr, this);
  }

  public void setZone(SWIGTYPE_p_float value) {
    faust_dspJNI.Para_zone_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getZone() {
    long cPtr = faust_dspJNI.Para_zone_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public Para() {
    this(faust_dspJNI.new_Para(), true);
  }

}
